// AUTO-GENERATED from WGSL\mousecircle_overlay_fragment.wgsl
// Generated by: shader_compiler (Naga 0.1.0)
// DO NOT EDIT - Modify the source WGSL file instead

struct VertexOutput {
    float4 color : TEXCOORD0;
    float4 position : SV_Position;
};

float4 main(VertexOutput input) : SV_Target0
{
    return input.color;
}
