// AUTO-GENERATED from WGSL/mousecircle_scene_vertex.wgsl
// Generated by: shader_compiler (Naga 0.1.0)
// DO NOT EDIT - Modify the source WGSL file instead

struct SceneUniforms {
    row_major float4x4 mvp;
    float4 cameraPos;
    float4 fogColor;
};

struct VertexInput {
    float3 position : LOC0;
    float surfaceType : LOC1;
    float2 uv : LOC2;
    float3 normal : LOC3;
};

struct VertexOutput {
    float4 position : SV_Position;
    float surfaceType : LOC0;
    float2 uv : LOC1;
    float3 normal : LOC2;
    float3 worldPos : LOC3;
};


struct VertexOutput_main {
    float surfaceType : LOC0;
    float2 uv : LOC1;
    float3 normal : LOC2;
    float3 worldPos : LOC3;
    float4 position : SV_Position;
};

