// AUTO-GENERATED from WGSL\mousecircle_overlay_vertex.wgsl
// Generated by: shader_compiler (Naga 0.1.0)
// DO NOT EDIT - Modify the source WGSL file instead

struct VertexInput {
    float2 position : TEXCOORD0;
    float4 color : TEXCOORD1;
};

struct VertexOutput {
    float4 position : SV_Position;
    float4 color : TEXCOORD0;
};

struct VertexOutput_main {
    float4 color : TEXCOORD0;
    float4 position : SV_Position;
};

VertexOutput_main main(VertexInput input)
{
    VertexOutput output = (VertexOutput)0;

    output.position = float4(input.position, 0.0, 1.0);
    output.color = input.color;
    VertexOutput _e9 = output;
    const VertexOutput vertexoutput = _e9;
    const VertexOutput_main vertexoutput_1 = { vertexoutput.color, vertexoutput.position };
    return vertexoutput_1;
}
