// AUTO-GENERATED from WGSL\mousecircle_overlay_fragment.wgsl
// Generated by: shader_compiler (Naga 0.1.0)
// DO NOT EDIT - Modify the source WGSL file instead

struct VertexOutput {
    float4 position : SV_Position;
    float4 color : TEXCOORD0;
};

struct FragmentInput_main {
    float4 color : TEXCOORD0;
    float4 position : SV_Position;
};

float4 main(FragmentInput_main fragmentinput_main) : SV_Target0
{
    VertexOutput input = { fragmentinput_main.position, fragmentinput_main.color };
    return input.color;
}
