// AUTO-GENERATED from WGSL/mousecircle_scene_vertex.wgsl
// Generated by: shader_compiler (Naga 0.1.0)
// DO NOT EDIT - Modify the source WGSL file instead

struct SceneUniforms {
    row_major float4x4 mvp;
    float4 cameraPos;
    float4 fogColor;
    float4 staticLights[16];
    float4 staticLightColors[16];
    float4 staticLightParams;
    float4 flashlightPos;
    float4 flashlightDir;
    float4 flashlightParams;
    float4 screenParams;
    float4 ceilingLightEmissive;
    float4 ceilingLightDiffuser;
};

struct VertexInput {
    float3 position : TEXCOORD0;
    float surfaceType : TEXCOORD1;
    float2 uv : TEXCOORD2;
    float3 normal : TEXCOORD3;
};

struct VertexOutput {
    float4 position : SV_Position;
    float surfaceType : TEXCOORD0;
    float2 uv : TEXCOORD1;
    float3 normal : TEXCOORD2;
    float3 worldPos : TEXCOORD3;
};

static const uint MAX_STATIC_LIGHTS = 16u;

cbuffer SceneUniforms : register(b0, space1) {
    row_major float4x4 mvp;
    float4 cameraPos;
    float4 fogColor;
    float4 staticLights[16];
    float4 staticLightColors[16];
    float4 staticLightParams;
    float4 flashlightPos;
    float4 flashlightDir;
    float4 flashlightParams;
    float4 screenParams;
    float4 ceilingLightEmissive;
    float4 ceilingLightDiffuser;
}

struct VertexOutput_main {
    float surfaceType : TEXCOORD0;
    float2 uv : TEXCOORD1;
    float3 normal : TEXCOORD2;
    float3 worldPos : TEXCOORD3;
    float4 position : SV_Position;
};

VertexOutput_main main_(VertexInput input)
{
    VertexOutput output = (VertexOutput)0;

    float4 world = float4(input.position, 1.0);
    float4x4 _e8 = mvp;
    output.position = mul(world, _e8);
    output.surfaceType = input.surfaceType;
    output.uv = input.uv;
    output.normal = input.normal;
    output.worldPos = input.position;
    VertexOutput _e18 = output;
    const VertexOutput vertexoutput = _e18;
    const VertexOutput_main vertexoutput_1 = { vertexoutput.surfaceType, vertexoutput.uv, vertexoutput.normal, vertexoutput.worldPos, vertexoutput.position };
    return vertexoutput_1;
}
